# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='bid_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_price',
            field=models.IntegerField(null=True),
        ),
    ]
